# Generated by Django 6.1 on 2026-09-01 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
        ('relationships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.JSONField(default=list)),
                ('energy', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('time_vibe', models.CharField(max_length=30)),
                ('planning_type', models.CharField(choices=[('TOGETHER', 'We plan'), ('SURPRISE', 'You surprise me')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING_FOR_PLANNER', 'Waiting for planner'), ('PLANNED', 'Planned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('google_event_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='places.place')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='relationships.relationship')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
