# Generated by Django 6.1 on 2026-09-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='location_revealed',
            field=models.BooleanField(default=True),
        ),
    ]
